# Generated by Django 3.1.6 on 2021-02-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('charges', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
