# Generated by Django 3.1.6 on 2021-02-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20210202_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
